### ISSUE TITLE
Duplicate Push Notification Android 

### ISSUE THREAD

**Issue by hbabhishek** [ParsePlatform/Parse-SDK-Android#178] opened 2015-10-07 06:35 UTC
When user uninstalls the app and installs it again it creates a duplicate installation object for the same device. This behavior creates while broadcasting push notifications.

When we broadcast a push notification from Parse push notification campaign some users get duplicate notifications. One user got same notification 10 times. 

Please look into the issue and advise us how to overcome the issue.

NOTE: We are using Parse SDK version 1.7.1

**Comment by grantland** [comment] 2015-10-07 22:19
Closing as duplicate of #173.

**Closed by grantland** 2015-10-07 22:19 UTC

**Comment by hbabhishek** [comment] 2015-10-08 07:42
This issue is not a duplicate of #173. This happens when we broadcast push from Parse push notification tab. And it is generated by duplicate installation objects for same devices. 

Please re-open it and provide us some solution.

**Comment by grantland** [comment] 2015-10-08 19:13
Your report, #173, was also about duplicate push notifications. How is this different?

**Comment by hbabhishek** [comment] 2015-10-09 10:01
When user uninstalls the app and installs it again it creates a duplicate installation object for the same device. This behavior creates problem while broadcasting push notifications.

When we broadcast a push notification from Parse push notification campaign some users get duplicate notifications. One user got same notification 10 times.

**Comment by grantland** [comment] 2015-10-14 20:57
* Could this be cause of #173?
* What do you mean by "duplicate"? Do they have the same deviceToken or does it have a completely new ParseInstallation?
