### ISSUE TITLE
SSL Certificate Expired while trying to build

### ISSUE THREAD

**Issue by barchard** [ParsePlatform/Parse-SDK-Android#463] opened 2016-05-26 17:03 UTC
Hi, I am currently receiving a Gradle error while trying to build. It looks like the certificate has expired:

```
Caused by: org.gradle.internal.resource.transport.http.HttpRequestException: Could not GET 'https://maven.parse.com/repo/com/parse/tools/gradle/maven-metadata.xml'.
```

Gradle:

```
buildscript {
    repositories {
        mavenCentral()
        maven {
            url 'https://maven.parse.com/repo'
        }
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath 'com.parse.tools:gradle:1.+'
        classpath 'io.fabric.tools:gradle:1.+'
    }
}
```

Changing the url to http://maven.parse.com/repo does not fix the issue as http is being redirect to https.

<img width="516" alt="screen shot 2016-05-26 at 1 03 08 pm" src="https://cloud.githubusercontent.com/assets/17622/15583095/3e2b941e-2342-11e6-825b-0340fcd30310.png">

**Comment by grantland** [comment] 2016-05-26 17:36
This seems to be an issue with Parse's Gradle plugin, which is not part of Parse-Android-SDK, so I'll be closing this issue.

In either case, Parse is shutting down their services so I wouldn't be surprised if they stop hosting their Gradle plugin as well. Since it's only used for Parse Crash Reporting and that feature has been deprecated for almost a year now, I'd say the best option is to remove all traces of Parse Crash Reporting, including the Gradle plugin, from your application.

**Closed by grantland** 2016-05-26 17:36 UTC

**Comment by mliberato** [comment] 2016-05-30 13:58
Can't build any project. We still have time until complete shutdown. I think Parse should renew its certificate or at least allow us to use HTTP instead of HTTPS.

**Comment by badjano** [comment] 2016-05-30 14:01
bump

**Comment by grantland** [comment] 2016-05-31 17:14
@mliberato @badjano have either of you read my explanation or workaround?

**Comment by mliberato** [comment] 2016-05-31 18:00
Thanks @grantland. I haven't noticed that gradle plugin was used only by Parse Crash Report, which I don't use at all. I can confirm it is working by just removing the gradle plugin from my app.
Sorry for the confusion.
