### ISSUE TITLE
Getting stale data when querying from LDS and then network

### ISSUE THREAD

**Issue by zhoul-HS** [ParsePlatform/Parse-SDK-Android#302] opened 2015-12-16 12:59 UTC
I'm using the latest version to query data from parse, but if I pin query results to the localDataStore, then change a field (String) in the parse web console, and query again, I'm getting the old data from the query.

After debugging, it seems that I get the correct JSON, which is parsed to a State object, and then the `rebuildEstimatedData` method of ParseObjects updates estimatedData to the correct data, but in the same method, an operation from operationSetQueue reverts it to the stale data.
```java
  private void rebuildEstimatedData() {
    synchronized (mutex) {
      estimatedData.clear();
      for (String key : state.keySet()) {
        estimatedData.put(key, state.get(key));
      }
      for (ParseOperationSet operations : operationSetQueue) {
        applyOperations(operations, estimatedData); // This is the culprit
      }
    }
  }
```

Now I'm in debugging brain overload, so I'm reaching out. I don't really understand the mechanism, and can't figure out what causes this operation to run.

A few pointers:
* I use synchronous query.find on a manual background thread, but it seems to happen if i use findInBackground too, I then unpin using a tag and repin the results.
* If I unpin with the tag I pinned on application startup everything works as expected.
 
Help.

**Comment by zhoul-HS** [comment] 2015-12-16 15:23
#294 helped me get to the root of the problem.
I have a step of mapping the parse object to our BL entity, and then right away mapping back to parse object for caching in the local datastore. it calls a lot of "sets" in the parse object, which marks the object as dirty, even though the data hasn't changed (!).
I don't know why and how, but the dirty state is saved to the local datastore, in a way that even after application restart, when I query the network, it fetches from the network but gets the 'dirty' object and shows it to me.

This was confusing.
Conclusions:
* This behavior around "dirty" state should be documented! specifically fetching from the network and getting dirty objects from the LDS
* Maybe we as users need more control? I use the LDS for easier disk caching and not for offline usage - so I need the ability to have a global or granular way to revert dirty changes automatically  or on demand (app restart, activity destroy).

**Comment by grantland** [comment] 2015-12-16 20:02
You're correct, this is the expected behavior.

> This behavior around "dirty" state should be documented! specifically fetching from the network and getting dirty objects from the LDS

We haven't really found a good way to describe this, but our code (which we use to generate JavaDocs) and our documentation are all open source and we'd welcome PRs to help make this more clear.

> Maybe we as users need more control? I use the LDS for easier disk caching and not for offline usage - so I need the ability to have a global or granular way to revert dirty changes automatically or on demand (app restart, activity destroy).

We try to allow as much control as possible, in this case with the use of `ParseObject#isDirty()`, `#isDirty(key)`, `#revert()`, and `#revert(key)`. With these you should be able to detect unwanted dirty changes and revert to the snapshot received from the server.

> ParseObjects whose data hasn't changed shouldn't be marked as dirty. Data change should mark objects as dirty, not pending operations.

This is working as expected. We don't transmit keys that haven't been changed as in those which haven't been called `#put(key, value)`. This means that we do track and transmit keys which have been called `#put(key, sameValue)` since there are instances when you want to ensure that a key stays as a certain value or you want a beforeSave/afterSave hook triggered regardless of the previous value. You can workaround this by checking the value before calling `#put(key, value)` if you do not want this to happen.

**Comment by zhoul-HS** [comment] 2015-12-16 20:51
All valid points.

Can I ask what is the strategy of saving dirty objects to local store? the moment I use `#put`? if so... it will be hard to automatically revert changes (will need to track it somehow).

**Comment by grantland** [comment] 2015-12-17 00:48
I believe the only triggers for automatically updating the Local Datastore from within the SDK are save, delete, and fetch.

* Saves will update LDS regardless of success/failure, but will generally only persist objects with no dirty changes since the dirty changes would have been persisted and moved to the snapshot values. There few instances where it may persist dirty changes are failed saves and dirty changes made after the call to save but before it completed.
* Deletes will only update LDS on success deletes and will generally result in the object being removed from LDS.
* Fetch will only update LDS on success fetches. This has the highest chance of having dirty data persisted to LDS.

This can all be found in `ParseObject.java` by looking for calls to `OfflineStore#updateDataForObjectAsync(object)`: https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParseObject.java#L1417

**Comment by zhoul-HS** [comment] 2015-12-17 07:42
And I believe also doing a #pin/#pinInBackground for dirty object saves it as dirty to the LDS? (which is what caused my problem)

**Comment by grantland** [comment] 2015-12-17 08:13
Yes, pinning will persist the dirty state as well. Sorry, I only mentioned the magical ones under the hood and failed to mention the developer initiated ones.

**Comment by grantland** [comment] 2015-12-17 19:46
I'll be closing this issue since it seems like it's been resolved, but feel free to reopen it if this isn't the case.

**Closed by grantland** 2015-12-17 19:46 UTC
Labels: question
