### ISSUE TITLE
Runtime Exception Could not create ParseKeyValueCache directory

### ISSUE THREAD

**Issue by MNDaveC** [ParsePlatform/Parse-SDK-Android#395] opened 2016-02-10 22:00 UTC
As of updating my app to SDK 1.11.0 I am getting this runtime exception... what conditions cause this to occur? Any fix?

https://github.com/ParsePlatform/Parse-SDK-Android/blob/21fb42133a16dd25c415af836cb46992212ac4fd/Parse/src/main/java/com/parse/ParseKeyValueCache.java#L61

**Comment by grantland** [comment] 2016-02-10 22:15
It means exactly what is right above it: `<cache_dir>/ParseKeyValueCache` is not a directory and we were not able to create it as a directory.

Most likely the cache directory has incorrect permissions, something else has created a file `ParseKeyValueCache`, or the OS is freaking out. None of which is a problem of the SDK, nor can be resolved by the SDK.

**Closed by grantland** 2016-02-10 22:15 UTC

**Comment by arturwest** [comment] 2019-02-02 09:44
<img width="1168" alt="screen shot 2019-02-02 at 11 40 21 am" src="https://user-images.githubusercontent.com/16718070/52162602-65dc2700-26df-11e9-929e-51636b3344bc.png">
What should i do, when every 20th user has this issue?

**Comment by Jawnnypoo** [comment] 2019-02-04 15:07
Post the stacktrace, list out the common devices it occurs on, attempt debugging of the issue, potentially acquire one of the devices it occurs on to reproduce. There are many things you can do.

**Comment by arturwest** [comment] 2019-02-04 15:24
Caused by java.lang.RuntimeException
Could not create ParseKeyValueCache directory

com.parse.ParseKeyValueCache.initialize (ParseKeyValueCache.java:58)
com.parse.ParseKeyValueCache.initialize (ParseKeyValueCache.java:52)
com.parse.Parse.initialize (Parse.java:153)
com.parse.Parse.initialize (Parse.java:124)
com.mypackagename.ApplicationClass.onCreate (ApplicationClass.kt:42)
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1028)
android.app.ActivityThread.handleBindApplication (ActivityThread.java:5730)
android.app.ActivityThread.-wrap2 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1640)
android.os.Handler.dispatchMessage (Handler.java:105)
android.os.Looper.loop (Looper.java:156)
android.app.ActivityThread.main (ActivityThread.java:6595)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:942)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:832)

<img width="862" alt="screen shot 2019-02-04 at 5 19 11 pm" src="https://user-images.githubusercontent.com/16718070/52217411-0c235a80-28a1-11e9-8a23-d0bddef76454.png">

No specific pattern can be traced if you consider the device or version. This crash happens on many devices.

**Comment by Jawnnypoo** [comment] 2019-02-22 15:28
I think more exploration needs to be done before we can attempt to fix anything here. We need to know what the commonality is between these devices. It could be something like each of these devices has microSD cards, which the app is installed on, and then the SD card is removed, or something similar. If we can get clear reproduction steps, we can fix it.

**Comment by arturwest** [comment] 2019-02-22 15:53
@Jawnnypoo I think that the problem is in context.getCacheDir(). At the moment of initialization `initialize(new File(context.getCacheDir(), DIR_NAME));` context.getCacheDir() returns null. The only pattern is that this happend only on API 21+. Can we create another initialize method that will allow developers pass their files instances created by themselves? Or maybe use another directory to store cache.

**Comment by Jawnnypoo** [comment] 2019-02-22 16:24
The docs say nothing about context.getCacheDir() ever returning null: https://developer.android.com/reference/android/content/Context.html#getCacheDir()

I am not sure that that is what is happening here.
