### ISSUE TITLE
Proposal: Remove in-memory cache for ParseFile

### ISSUE THREAD

**Issue by wangmengyan95** [ParsePlatform/Parse-SDK-Android#118] opened 2015-09-09 04:24 UTC
Right now we keep a in-memory cache for `ParseFile`. Doing this will increase `ParseFile` performance in some cases, but it consumes too much memory. This not only downgrades the whole app's performance in some cases but also prevents us from allowing developers to upload/download file that large than 10 MB. After careful consideration and our recent changes to `ParseFile` related classes (`ParseFileController` #73 , `ParseHttpBody` #70 and `ParseFile` #116). We propose to remove the in-memory cache for `ParseFile`.

Pros:
1. Allowing uploading and downloading files that large than 10MB(current limitation)
2. Much less memory usage
We do an experiment with uploading and downloading 20 1MB ParseFile, see the memory consumption result
Upload
With in-memory cache
![test](https://cloud.githubusercontent.com/assets/4666935/9753281/530d97d8-566f-11e5-90f6-70c8b693b892.png)
Without in-memory cache
![test](https://cloud.githubusercontent.com/assets/4666935/9753295/74f9ed9c-566f-11e5-8cb2-a266b8dbce97.png)

Download
With in-memory cache
![test](https://cloud.githubusercontent.com/assets/4666935/9753301/96aade4c-566f-11e5-8951-242e1c69bd94.png)
Without in-memory cache
![test](https://cloud.githubusercontent.com/assets/4666935/9753308/ac1639f2-566f-11e5-991f-fa74caa98cf0.png)

Cons:
1. Decrease performance since we use in-disk cache instead of in-memory cache

Please leave your suggestions and feedbacks.
Check PR #116 for details.

**Comment by faradaj** [comment] 2015-09-22 22:53
A great way of doing open-source, 👏🏻.
I think this enhancement has two major aspects:
• Making 'ParseFile-operating apps' smoother.
• Making 'ParseFile-operating apps' respectful to Android.
which are musts for *good* Android apps.
Seems like a fix rather than an enhancement.
+1

**Comment by aminelaadhari** [comment] 2015-10-22 15:13
@grantland when the release 1.10.4 is planned ? 
99% of our OOM issues are related to this.

**Comment by grantland** [comment] 2015-11-10 00:11
@aminelaadhari Unfortunately we don't have an ETA right now for the next release.

In addition, the stacktraces from OOM exceptions generally don't point to the root cause of the problem, but are just signals that you have bad memory management somewhere else in your application. It'd be worthwhile to trace your application to see if there is allocation thrashing somewhere.

**Comment by grantland** [comment] 2015-11-11 21:50
Resolved in #116

**Closed by grantland** 2015-11-11 21:50 UTC
Labels: enhancement, proposal
