### ISSUE TITLE
ParseQuery gives no indication that incomplete results returned

### ISSUE THREAD

**Issue by ajfclark** [ParsePlatform/Parse-SDK-Android#225] opened 2015-10-29 06:23 UTC
When a query returns more results than .setLimit() allows, the query class makes no indication that more data is waiting, it just silently returns an abbreviated dataset. I'm not sure this is what most users of other data backends would be used to?

It would be useful if it alerted somehow that there were more results pending.  Perhaps by expanding findCallback(objects, throwable) to have a boolean like moreData or maybe by raising an exception?

As an aside, when making the same query to the same data source on different devices, it would be useful if the same dataset was returned. I just spent some time chasing my tail looking for a device issue because the result set returned on the two devices was different which led to different symptoms.

**Comment by wangmengyan95** [comment] 2015-10-29 17:40
Hi @ajfclark, the issue of this approach is during the period of the current query and next query, the dataset may change. So even we give some indications about whether there are more results, it just represents the current state of the dataset, not the state when you do next query. That is why we do not do this right now.

**Comment by ajfclark** [comment] 2015-10-30 00:46
At the moment, it feels like a silent failure. I never get the opportunity to increase my limit and requery or handle the issue cleanly. It would be helpful if there was a way to pick up that the result set returned is not actually the result set you queried for.

**Comment by grantland** [comment] 2015-11-04 00:39
Unfortunately, there's no functionality for returning this flag in our REST API. How many results are you receiving? We have a documented limit of 1000 for all queries and you can use some rough logic to implement paging for collections larger than 1000.

**Comment by ajfclark** [comment] 2015-11-04 04:33
I understand that there's some simple logic that can be implemented to requery whenever the limit is returned, it just seems weird that there's no flag to indicate that the backend hasn't actually done what you asked.

**Comment by grantland** [comment] 2015-11-04 05:03
Thanks for your feedback, but I'm going to close this issue since it's not a bug, not a feature we're going to implement and can easily be worked around.

**Closed by grantland** 2015-11-04 05:03 UTC
Labels: question
