### ISSUE TITLE
ParseInstalltion isn't updated when app version changes

### ISSUE THREAD

**Issue by Shailevy** [ParsePlatform/Parse-SDK-Android#24] opened 2015-08-17 07:29 UTC
When my users updates the app I call ParseInstallation.getCurrentInstallation().saveInBackground but the SDK won't trigger a call to the server, this causes the appVersion fields in the Installation table to be incorrect

By overviewing the code (thanks for open-sourcing) it seems to be by design (Nothing has really changed in the Installation so updateBeforeSave doesn't trigger.

Please explain this

**Comment by grantland** [comment] 2015-08-17 16:50
You're correct, this is by design. We do this to prevent your app from DDOSing yourself when releasing app updates, since app updates and new app runs occur around the same time for all users and it would cause a spike that may lead you to run over your req/s limit.

**Comment by Shailevy** [comment] 2015-08-18 17:30
Thanks, In that case, if I agree to the spike risk can you please explain how do I manually force this update ?

**Comment by grantland** [comment] 2015-08-18 18:06
`ParseInstallation`'s `appVersion` gets updated in `updateBeforeSave`: https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParseInstallation.java#L109
`ParseObject`'s `updateBefore` save only gets called if the object is dirty: https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParseObject.java#L1605

So making your current `ParseInstallation` dirty whenever you want it updated would do the trick. Probably along with some logic that would only dirty the `ParseInstallation` when your app's `versionName` or `versionCode` changes.

**Comment by Shailevy** [comment] 2015-08-19 07:07
Ok,
I hope you guys will provide a setIsDirty(boolean)  function at some point.
But please document these behaviour better on the docs site.

I guess this item can be closed, thanks a lot :)

**Comment by grantland** [comment] 2015-08-19 07:17
You don't need a `setIsDirty(boolean)`, you can just change any field on the `ParseInstallation` via `#put(String, Object)`.

Our docs are actually open sourced [here][docs] and I've created an [issue][issue] for it, but feel free to submit a pull request with updated documentation as well.

And no problem, glad to help! I'll be closing this issue now.

 [docs]: https://github.com/ParsePlatform/Docs
 [issue]: https://github.com/ParsePlatform/Docs/issues/174

**Closed by grantland** 2015-08-19 07:17 UTC
Labels: question
