### ISSUE TITLE
com.parse.ParseRequest$ParseRequestException: i/o failure

### ISSUE THREAD

**Issue by madkid66** [ParsePlatform/Parse-SDK-Android#431] opened 2016-03-31 23:39 UTC
Am getting the following exception most of the times when querying for data. Am using 1.13.0 version of parse android sdk. Please suggest any solution at the earliest.

 at com.parse.ParseRequest.newTemporaryException(ParseRequest.java:290)
            at com.parse.ParseRequest$2.then(ParseRequest.java:145)
            at com.parse.ParseRequest$2.then(ParseRequest.java:139)
            at bolts.Task$15.run(Task.java:917)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.net.SocketTimeoutException: Read timed out
            at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
            at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:753)
            at com.android.okio.Okio$2.read(Okio.java:116)
            at com.android.okio.RealBufferedSource.indexOf(RealBufferedSource.java:150)
            at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:97)
            at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:202)
            at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:119)
            at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:798)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:405)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:349)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:517)
            at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
            at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
            at com.parse.ParseURLConnectionHttpClient.getResponse(ParseURLConnectionHttpClient.java:106)
            at com.parse.ParseURLConnectionHttpClient.executeInternal(ParseURLConnectionHttpClient.java:57)
            at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:158)
            at com.parse.ParsePlugins$1.intercept(ParsePlugins.java:115)
            at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:147)
            at com.parse.ParseHttpClient.execute(ParseHttpClient.java:122)
            at com.parse.ParseRequest$3.then(ParseRequest.java:136)
            at com.parse.ParseRequest$3.then(ParseRequest.java:133)
            at bolts.Task$15.run(Task.java:917)
            at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
            at bolts.Task.completeAfterTask(Task.java:908)
            at bolts.Task.continueWithTask(Task.java:715)
            at bolts.Task.continueWithTask(Task.java:726)
            at bolts.Task$13.then(Task.java:818)
            at bolts.Task$13.then(Task.java:806)
            at bolts.Task$15.run(Task.java:917)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by sprabs** [comment] 2016-04-01 01:27
I'm actually hitting a similar issue when querying a large amount of data. @grantland do you know what may be going wrong? I was originally using 1.12.0 when I saw the issue and updated the SDK, but I'm still hitting the same problem.

**Comment by alokomkar** [comment] 2016-10-14 09:45
Any solution for this?

**Comment by lxknvlk** [comment] 2016-10-14 09:46
i have i/o failure errors when parse server or my database were not working good

**Comment by tsvetann** [comment] 2016-12-05 22:37
I just got this same error now. The reason was the phone I was testing on was offline. I was using: 
`user.signUpInBackground`. After re-activating wifi on the phone all works as normal. The question is what is the proper way to handle such situation from user perspective?

**Comment by paatz04** [comment] 2016-12-14 03:15
I'm having the same issue and upgrading to 1.13.1 and 1.4.0 didn't solve the issue. It is working in the simulator and on iOS devices.
Working on Android 6 not working on API 22

**Comment by anthonycmain** [comment] 2017-01-17 17:22
We are having the same issue, our Parse Server is serving fine to iOS and JS clients, but Android is failing

**Comment by kiaanpillay** [comment] 2017-01-17 19:40
Same issue on Android 1.13.1

**Comment by contervis** [comment] 2017-01-19 20:01
Same issue on Android 1.13.1 and ParseServer 2.3.2 when call "signUpInBackground" on a new user

**Comment by anthonycmain** [comment] 2017-01-19 20:04
We've found turning off SSL fixes it so it must be related to the SSL layer

**Comment by contervis** [comment] 2017-01-19 20:07
Thanks for the tip, unfortunately we need SSL to be active in order to keep safe our user base traffic data.

**Comment by contervis** [comment] 2017-01-19 20:13
UPDATE:
Event with Parse-SDK-Android version 1.13.0, having parse-server version 2.3.2 still cause the same problem.

**Comment by anthonycmain** [comment] 2017-01-19 20:27
So do we, but the particular SSL setup I think is the problem, we will be trying something different next week. Might be worth doing the same

**Comment by paatz04** [comment] 2017-01-19 20:37
Alright so what happens is the following:
The parse SDK uses OKHttp as network library for android version above x.x. Below x.x (can't remember what the exact version is) it uses a different fallback network library (don't know why)
The fallback network library fails with cheap SSL certificates, so either you change the parse SDK code so that you fallback to a different network library that supports the certificates, or you upgrade your certificate which worked in our case.

**Comment by anthonycmain** [comment] 2017-01-19 20:46
This sounds valid to me, we have a cheap SSL on our staging server (can't remember its name, but we generate it through a script)

**Comment by devlinsmith** [comment] 2017-02-14 13:49
Is there any solution to this issue? I see 'cheap' SSL certificates seem to cause this, but the certificate I was issued was from a registered provider. I did do the chaining myself, but have had no problems on any other devices. Nor on any other services I use with my certificates chained this way, only on the Android Parse SDK.

EG: Retrofit uses okhttp and this exact device operates fine with that on a different project, and certificates chained in the same way.

@anthonycmain is there any feedback on "we will be trying something different next week"? Did you change out your certificates and see success?

Side Note: I can only reproduce this issue on Samsung J1 running 5.1.1. Haven't tested on **all devices.

**Comment by devlinsmith** [comment] 2017-02-17 09:43
Resolved my issue. Not related to Certificate. Another API call was having gateway timeouts which influenced the other API calls, resulting in them timing out and reporting this stack trace.

**Comment by rogerhu** [comment] 2017-03-08 19:58
Thanks.  Closing

**Closed by rogerhu** 2017-03-08 19:58 UTC

**Comment by anthonycmain** [comment] 2017-03-08 20:12
I've just been told by our team they have resolved issues but it was a different problem....

Facebook suggests you don't need the Parse SDK as a separate dependency but actually you do. Their reference is for an older version of the SDK.

So if you are using the Facebook SDK as well this might also be the cause. Make sure you directly reference Parse SDK too
