### ISSUE TITLE
Parse crash reporting doesn't work

### ISSUE THREAD

**Issue by Ishimilated** [ParsePlatform/Parse-SDK-Android#191] opened 2015-10-14 19:23 UTC
I use Parse 1.10.3 and ParseCrashReporting 1.10.3 and no crash gets displayed in the dashboard (testing on android devices 5.0.2 and 4.4.4). I get a NullPointerException right after it starts sending the report to Parse. I don't know it that's relevant, though.

This is my stacktrace:
```
10-14 21:03:50.811 31417-31417/com.my.app E/CrashReporting: ParseCrashReporting caught a RuntimeException exception for com.my.app. Building report.
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting: Handling exception for crash
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.my.app/com.my.app.MainActivity}: java.lang.RuntimeException: Test
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2790)
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2855)
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting:     at android.app.ActivityThread.access$900(ActivityThread.java:181)
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting:     at android.os.Looper.loop(Looper.java:145)
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting:     at android.app.ActivityThread.main(ActivityThread.java:6117)
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting:     at java.lang.reflect.Method.invoke(Native Method)
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting:     at java.lang.reflect.Method.invoke(Method.java:372)
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting:  Caused by: java.lang.RuntimeException: Test
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting:     at com.my.app.MainActivity.onCreate(MainActivity.java:194)
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting:     at android.app.Activity.performCreate(Activity.java:6374)
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2743)
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2855) 
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting:     at android.app.ActivityThread.access$900(ActivityThread.java:181) 
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474) 
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting:     at android.os.Handler.dispatchMessage(Handler.java:102) 
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting:     at android.os.Looper.loop(Looper.java:145) 
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting:     at android.app.ActivityThread.main(ActivityThread.java:6117) 
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting:     at java.lang.reflect.Method.invoke(Native Method) 
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting:     at java.lang.reflect.Method.invoke(Method.java:372) 
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
10-14 21:03:50.816 31417-31417/com.my.app E/CrashReporting:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) 
10-14 21:03:50.816 31417-31417/com.my.app D/CrashReporting: Generating report file for crash
10-14 21:03:50.901 31417-31417/com.my.app D/CrashReporting: Retrieving logcat output...
10-14 21:03:50.971 31417-31417/com.my.app D/CrashReporting: Retrieving logcat output...
10-14 21:03:51.021 31417-31417/com.my.app D/CrashReporting: Retrieving logcat output...
10-14 21:03:51.261 2763-2942/? W/ActivityManager: Activity pause timeout for ActivityRecord{2e9ccc00 u0 com.my.app/.MainActivity t1543}
10-14 21:03:51.491 31417-31417/com.my.app W/Settings: Setting font_size has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
10-14 21:03:52.086 31417-31417/com.my.app W/Settings: Setting wifi_saved_state has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
10-14 21:03:52.101 31417-31417/com.my.app V/CrashReporting: About to start ReportSenderWorker from #handleException
10-14 21:03:52.106 31417-31478/com.my.app D/CrashReporting: #checkAndSendReports - start
10-14 21:03:52.106 31417-31478/com.my.app D/CrashReporting: Looking for error files in /data/data/com.my.app/files/com.parse/cr/reports
10-14 21:03:52.106 31417-31478/com.my.app D/CrashReporting: Loading file 1444849430821-RuntimeException-1.stacktrace
10-14 21:03:52.136 31417-31478/com.my.app I/CrashReporting: Sending file 1444849430821-RuntimeException-1.stacktrace
10-14 21:03:52.136 31417-31478/com.my.app D/CrashReporting: Sending crash report to Parse...
10-14 21:03:52.146 31417-31478/com.my.app D/CrashReporting: #checkAndSendReports - finish
10-14 21:03:52.171 31417-31479/com.my.app I/System.out: (HTTPLog)-Static: (This is just Trace Log)java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
10-14 21:03:52.171 31417-31479/com.my.app I/System.out:     at com.android.okhttp.internal.http.SBServiceAPI.getService(SBServiceAPI.java:641)
10-14 21:03:52.171 31417-31479/com.my.app I/System.out:     at com.android.okhttp.internal.http.HttpEngine.<init>(HttpEngine.java:211)
10-14 21:03:52.171 31417-31479/com.my.app I/System.out:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.newHttpEngine(HttpURLConnectionImpl.java:332)
10-14 21:03:52.171 31417-31479/com.my.app I/System.out:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.initHttpEngine(HttpURLConnectionImpl.java:283)
10-14 21:03:52.171 31417-31479/com.my.app I/System.out:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:107)
10-14 21:03:52.171 31417-31479/com.my.app I/System.out:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:221)
10-14 21:03:52.171 31417-31479/com.my.app I/System.out:     at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
10-14 21:03:52.171 31417-31479/com.my.app I/System.out:     at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
10-14 21:03:52.171 31417-31479/com.my.app I/System.out:     at com.parse.ParseURLConnectionHttpClient.executeInternal(ParseURLConnectionHttpClient.java:51)
10-14 21:03:52.171 31417-31479/com.my.app I/System.out:     at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:158)
10-14 21:03:52.171 31417-31479/com.my.app I/System.out:     at com.parse.ParsePlugins$1.intercept(ParsePlugins.java:115)
10-14 21:03:52.171 31417-31479/com.my.app I/System.out:     at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:147)
10-14 21:03:52.171 31417-31479/com.my.app I/System.out:     at com.parse.ParseHttpClient.execute(ParseHttpClient.java:122)
10-14 21:03:52.171 31417-31479/com.my.app I/System.out:     at com.parse.ParseRequest$3.then(ParseRequest.java:150)
10-14 21:03:52.171 31417-31479/com.my.app I/System.out:     at com.parse.ParseRequest$3.then(ParseRequest.java:147)
10-14 21:03:52.171 31417-31479/com.my.app I/System.out:     at bolts.Task$15.run(Task.java:825)
10-14 21:03:52.171 31417-31479/com.my.app I/System.out:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
10-14 21:03:52.171 31417-31479/com.my.app I/System.out:     at bolts.Task.completeAfterTask(Task.java:816)
10-14 21:03:52.171 31417-31479/com.my.app I/System.out:     at bolts.Task.continueWithTask(Task.java:628)
10-14 21:03:52.171 31417-31479/com.my.app I/System.out:     at bolts.Task.continueWithTask(Task.java:639)
10-14 21:03:52.171 31417-31479/com.my.app I/System.out:     at bolts.Task$13.then(Task.java:731)
10-14 21:03:52.171 31417-31479/com.my.app I/System.out:     at bolts.Task$13.then(Task.java:719)
10-14 21:03:52.171 31417-31479/com.my.app I/System.out:     at bolts.Task$15.run(Task.java:825)
10-14 21:03:52.171 31417-31479/com.my.app I/System.out:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-14 21:03:52.171 31417-31479/com.my.app I/System.out:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-14 21:03:52.171 31417-31479/com.my.app I/System.out:     at java.lang.Thread.run(Thread.java:818)
10-14 21:03:52.176 31417-31479/com.my.app I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-14 21:03:52.176 31417-31479/com.my.app I/System.out: (HTTPLog)-Static: isShipBuild true
10-14 21:03:52.176 31417-31479/com.my.app I/System.out: (HTTPLog)-Thread-40027-363996589: SmartBonding Enabling is false, SHIP_BUILD is true, log to file is false, DBG is false
10-14 21:03:52.176 31417-31479/com.my.app I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime: FATAL EXCEPTION: main
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime: Process: com.my.app, PID: 31417
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.my.app/com.my.app.MainActivity}: java.lang.RuntimeException: Test
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2790)
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2855)
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime:     at android.app.ActivityThread.access$900(ActivityThread.java:181)
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:145)
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6117)
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime:  Caused by: java.lang.RuntimeException: Test
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime:     at com.my.app.MainActivity.onCreate(MainActivity.java:194)
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:6374)
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2743)
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2855) 
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime:     at android.app.ActivityThread.access$900(ActivityThread.java:181) 
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474) 
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:145) 
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6117) 
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
10-14 21:03:52.201 31417-31417/com.my.app E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) 
10-14 21:03:52.201 2763-3698/? V/ApplicationPolicy: isApplicationStateBlocked userId 0 pkgname com.my.app
10-14 21:03:52.206 2763-3698/? W/ActivityManager:   Force finishing activity com.my.app/.MainActivity
10-14 21:03:52.206 2763-3698/? V/ApplicationPolicy: isApplicationStateBlocked userId 0 pkgname com.my.app
10-14 21:03:52.211 31417-31479/com.my.app I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
10-14 21:03:52.221 31417-31417/com.my.app I/Process: Sending signal. PID: 31417 SIG: 9
10-14 21:03:52.246 2763-2807/? I/ActivityManager: Process com.my.app (pid 31417)(adj 11) has died(49,428)
10-14 21:04:21.996 2763-2804/? W/ActivityManager: NORMAL SET : srcAppInfo.processName = com.android.systemui, destAppInfo.processName = com.my.app
10-14 21:04:22.021 2763-2804/? I/ActivityManager: Start proc com.my.app for broadcast com.my.app/com.parse.ParseBroadcastReceiver: pid=31758 uid=10261 gids={50261, 9997, 3003, 1028, 1015} abi=armeabi-v7a
10-14 21:04:22.106 31758-31758/com.my.app D/ActivityThread: Added TimaKeyStore provider
10-14 21:04:22.386 31758-31799/com.my.app I/System.out: (HTTPLog)-Static: (This is just Trace Log)java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
10-14 21:04:22.386 31758-31799/com.my.app I/System.out:     at com.android.okhttp.internal.http.SBServiceAPI.getService(SBServiceAPI.java:641)
10-14 21:04:22.386 31758-31799/com.my.app I/System.out:     at com.android.okhttp.internal.http.HttpEngine.<init>(HttpEngine.java:211)
10-14 21:04:22.386 31758-31799/com.my.app I/System.out:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.newHttpEngine(HttpURLConnectionImpl.java:332)
10-14 21:04:22.386 31758-31799/com.my.app I/System.out:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.initHttpEngine(HttpURLConnectionImpl.java:283)
10-14 21:04:22.386 31758-31799/com.my.app I/System.out:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:107)
10-14 21:04:22.386 31758-31799/com.my.app I/System.out:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:221)
10-14 21:04:22.386 31758-31799/com.my.app I/System.out:     at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
10-14 21:04:22.386 31758-31799/com.my.app I/System.out:     at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
10-14 21:04:22.386 31758-31799/com.my.app I/System.out:     at com.parse.ParseURLConnectionHttpClient.executeInternal(ParseURLConnectionHttpClient.java:51)
10-14 21:04:22.386 31758-31799/com.my.app I/System.out:     at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:158)
10-14 21:04:22.386 31758-31799/com.my.app I/System.out:     at com.parse.ParsePlugins$1.intercept(ParsePlugins.java:115)
10-14 21:04:22.386 31758-31799/com.my.app I/System.out:     at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:147)
10-14 21:04:22.386 31758-31799/com.my.app I/System.out:     at com.parse.ParseHttpClient.execute(ParseHttpClient.java:122)
10-14 21:04:22.386 31758-31799/com.my.app I/System.out:     at com.parse.ParseRequest$3.then(ParseRequest.java:150)
10-14 21:04:22.386 31758-31799/com.my.app I/System.out:     at com.parse.ParseRequest$3.then(ParseRequest.java:147)
10-14 21:04:22.391 31758-31799/com.my.app I/System.out:     at bolts.Task$15.run(Task.java:825)
10-14 21:04:22.391 31758-31799/com.my.app I/System.out:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
10-14 21:04:22.391 31758-31799/com.my.app I/System.out:     at bolts.Task.completeAfterTask(Task.java:816)
10-14 21:04:22.391 31758-31799/com.my.app I/System.out:     at bolts.Task.continueWithTask(Task.java:628)
10-14 21:04:22.391 31758-31799/com.my.app I/System.out:     at bolts.Task.continueWithTask(Task.java:639)
10-14 21:04:22.391 31758-31799/com.my.app I/System.out:     at bolts.Task$13.then(Task.java:731)
10-14 21:04:22.391 31758-31799/com.my.app I/System.out:     at bolts.Task$13.then(Task.java:719)
10-14 21:04:22.391 31758-31799/com.my.app I/System.out:     at bolts.Task$15.run(Task.java:825)
10-14 21:04:22.391 31758-31799/com.my.app I/System.out:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-14 21:04:22.391 31758-31799/com.my.app I/System.out:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-14 21:04:22.391 31758-31799/com.my.app I/System.out:     at java.lang.Thread.run(Thread.java:818)
10-14 21:04:22.391 31758-31799/com.my.app I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-14 21:04:22.391 31758-31799/com.my.app I/System.out: (HTTPLog)-Static: isShipBuild true
10-14 21:04:22.391 31758-31799/com.my.app I/System.out: (HTTPLog)-Thread-40034-283479452: SmartBonding Enabling is false, SHIP_BUILD is true, log to file is false, DBG is false
10-14 21:04:22.396 31758-31799/com.my.app I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-14 21:04:22.406 31758-31758/com.my.app D/CrashReporting: Crash reporting is enabled for com.my.app, initializing...
10-14 21:04:22.416 31758-31758/com.my.app D/CrashReporting: Looking for error files in /data/data/com.my.app/files/com.parse/cr/reports
10-14 21:04:22.416 31758-31758/com.my.app D/CrashReporting: Looking for error files in /data/data/com.my.app/files/com.parse/cr/minidumps
10-14 21:04:22.426 31758-31799/com.my.app I/System.out: KnoxVpnUidStorageknoxVpnSupported API value returned is false
```

**Comment by wkoszek** [comment] 2015-10-15 08:52
@Ishimilated Same here for iOS (ping @nlutsenko) and Android.
 
Just did integration for both Android with `Parse-1.10.3` and iOS with `parse-library-1.9.0` and `parse-library-1.8.0`. 

Enabled logging:

```
    [Parse setLogLevel:PFLogLevelDebug];
```

and I'm getting:

```
Oct 15 01:45:22 wkoszek-macbook Sensorama[45065]: [Info][Crash Reporting]: Did Send Crash Report for Date: 2015-10-15 08:45:12 +0000
Oct 15 01:45:22 wkoszek-macbook Sensorama[45065]: [Info][Crash Reporting]: Processed All Pending Crash Reports
```

But nothing on a Dashboard. The "Core" service worked OK, so did Analytics (but very slow).

CrashReporting isn't working for me.

**Comment by grantland** [comment] 2015-10-16 00:14
Judging by the logcat statements here:

```
10-14 21:03:50.816 31417-31417/com.my.app D/CrashReporting: Generating report file for crash
10-14 21:03:50.901 31417-31417/com.my.app D/CrashReporting: Retrieving logcat output...
10-14 21:03:50.971 31417-31417/com.my.app D/CrashReporting: Retrieving logcat output...
10-14 21:03:51.021 31417-31417/com.my.app D/CrashReporting: Retrieving logcat output...
10-14 21:03:51.261 2763-2942/? W/ActivityManager: Activity pause timeout for ActivityRecord{2e9ccc00 u0 com.my.app/.MainActivity t1543}
10-14 21:03:51.491 31417-31417/com.my.app W/Settings: Setting font_size has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
10-14 21:03:52.086 31417-31417/com.my.app W/Settings: Setting wifi_saved_state has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
10-14 21:03:52.101 31417-31417/com.my.app V/CrashReporting: About to start ReportSenderWorker from #handleException
10-14 21:03:52.106 31417-31478/com.my.app D/CrashReporting: #checkAndSendReports - start
10-14 21:03:52.106 31417-31478/com.my.app D/CrashReporting: Looking for error files in /data/data/com.my.app/files/com.parse/cr/reports
10-14 21:03:52.106 31417-31478/com.my.app D/CrashReporting: Loading file 1444849430821-RuntimeException-1.stacktrace
10-14 21:03:52.136 31417-31478/com.my.app I/CrashReporting: Sending file 1444849430821-RuntimeException-1.stacktrace
10-14 21:03:52.136 31417-31478/com.my.app D/CrashReporting: Sending crash report to Parse...
10-14 21:03:52.146 31417-31478/com.my.app D/CrashReporting: #checkAndSendReports - finish
```

and @wkoszek's report, it seems like this is a backend issue. 

To verify, could you both follow instructions [here](https://github.com/ParsePlatform/ParseInterceptors-Android/wiki/ParseLogInterceptor) enable networking logging (iOS instructions [here](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/wiki/Network-Debug-Tool)) and verify that the Crash Reporting requests succeed?

**Comment by wkoszek** [comment] 2015-10-16 16:20
Grantland,

You can't reproduce the issue? Clearly something is wrong, since many 
people report slowness of Parse webpage, Analytics and Crash reporting 
not working.

W.

**Comment by vedhavyas** [comment] 2015-10-16 17:37
even i have the same issue. it used to work but not anymore. crashes are being logged

**Comment by grantland** [comment] 2015-10-16 18:45
In order to properly triage this, we need to determine if this is actually a bug in the SDK or backend which requires the information in my previous post:

> To verify, could you both follow instructions [here](https://github.com/ParsePlatform/ParseInterceptors-Android/wiki/ParseLogInterceptor) enable networking logging (iOS instructions [here](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/wiki/Network-Debug-Tool)) and verify that the Crash Reporting requests succeed or fail?

**Comment by wkoszek** [comment] 2015-10-16 23:52
@grantland Can you confirm you can or can't reproduce it?

**Comment by Ishimilated** [comment] 2015-10-19 16:53
@grantland Thank you for your response. I followed the instructions and enabled network logging. I get an OK response every time the app crashes, so I think it gets sent to Parse. My crash dashboard is still empty though.

The log interceptor shows this (I just replaced the sent data with ... for privacy):
```
I/ParseLogInterceptor(32468): Type : Request
I/ParseLogInterceptor(32468): Request-Id : 0
I/ParseLogInterceptor(32468): Url : https://api.parse.com/1/events/_CrashReport
I/ParseLogInterceptor(32468): Method : POST
I/ParseLogInterceptor(32468): Headers : ...
I/ParseLogInterceptor(32468): Body : {
I/ParseLogInterceptor(32468):     "acraDump": { ...
I/ParseLogInterceptor(32468):     },
I/ParseLogInterceptor(32468):     "at": {
I/ParseLogInterceptor(32468):         "__type": "Date",
I/ParseLogInterceptor(32468):         "iso": "2015-10-19T13:03:38.023Z"
I/ParseLogInterceptor(32468):     }
I/ParseLogInterceptor(32468): }
I/ParseLogInterceptor(32468): --------------
I/ParseLogInterceptor(32468): Type : Response
I/ParseLogInterceptor(32468): Request-Id : 0
I/ParseLogInterceptor(32468): Status-Code : 200
I/ParseLogInterceptor(32468): Reason-Phrase : OK
I/ParseLogInterceptor(32468): Headers : {X-Runtime=0.114807, Content-Length=3, Access-Control-Allow-Methods=*, Connection=keep-alive, X-Android-Response-Source=NETWORK 200, Server=nginx/1.6.0, X-Android-Selected-Transport=http/
1.1, Date=Mon, 19 Oct 2015 13:03:39 GMT, Access-Control-Allow-Origin=*, X-Android-Received-Millis=1445259818792, X-Parse-Platform=G1, Content-Type=application/json; charset=utf-8, X-Android-Sent-Millis=1445259818438}
I/ParseLogInterceptor(32468): Body : {}
I/ParseLogInterceptor(32468): --------------
```

**Comment by grantland** [comment] 2015-10-19 18:14
@Ishimilated thanks for the information. This seems to be a backend issue, which we won't process through the SDK repository, so I'll be closing this. 

It actually looks like there's already a backend issue opened for a similar issue here: https://developers.facebook.com/bugs/821450024639735/

If this is not relevant, please open a backend issue by going to http://parse.com/help

**Closed by grantland** 2015-10-19 18:14 UTC
Labels: needs more info
