### ISSUE TITLE
Unable to receive data sent from iOS device on Android using ParsePush

### ISSUE THREAD

**Issue by bryanchoi** [ParsePlatform/Parse-SDK-Android#351] opened 2016-01-17 05:41 UTC
Hi, I'm trying to send custom data from an iOS device to Android using ParsePush. The push gets sent to an Android device fine, but there is no way for me to read the data payload. Below is a stackoverflow link with the details. Please tell me how I can receive custom data sent from iOS to Android device. I'd like to do reverse. Send custom data from Android device and have it read by iOS device. Thanks

http://stackoverflow.com/questions/34710023/how-to-send-custom-data-via-parse-push-notification-between-ios-and-android-devi

**Comment by wangmengyan95** [comment] 2016-01-19 18:27
You can use your custome subclass of `ParsePushBroadcastReceiver`, please check our tutorial [here](https://www.parse.com/docs/android/guide#push-notifications-receiving-pushes).

**Comment by bryanchoi** [comment] 2016-01-19 19:04
Hi I already viewed the tutorial, but it doesn't explain how I can get the
custom data dictionary I sent from iOS when I open the push notification on
the Android side. The only thing I'm seeing is the value for the alert
message.

Please advise.

Bryan

**Comment by wangmengyan95** [comment] 2016-01-19 21:31
Hi @bryanchoi, as we mentioned in the tutorial [here](https://www.parse.com/docs/android/guide#push-notifications-receiving-pushes), you can use your custome subclass of `ParsePushBroadcastReceiver`. In `onPushReceive`, you can get the push data by `String pushDataStr = intent.getStringExtra(KEY_PUSH_DATA);` like [here](https://github.com/ParsePlatform/Parse-SDK-Android/blob/1.12.0/Parse/src/main/java/com/parse/ParsePushBroadcastReceiver.java#L205).

**Comment by bryanchoi** [comment] 2016-01-20 00:14
Mengyan,

I am doing exactly what your tutorial mentions and all i see as pushDataStr
is: {"alert”:”John Doe requests to connect with
you.","push_hash":"5c48fe9e0314e1caca4430847b055860"}

Please advise. There is no data even though I am sending data from iOS.

Bryan

**Comment by bryanchoi** [comment] 2016-01-20 22:48
Hi, I never heard back on this issue. Can someone help me troubleshoot
please?

**Comment by grantland** [comment] 2016-01-21 18:30
Could you confirm that this problem reproduces when sending the same push to the Android client via REST or the dashboard?

**Comment by bryanchoi** [comment] 2016-01-21 18:32
How can I send custom data via the dashboard? I don't see that option in
the dropdown.

**Comment by grantland** [comment] 2016-01-21 19:04
In "Write your message" you can select JSON instead of text.

**Comment by wangmengyan95** [comment] 2016-01-21 19:10
Hi @bryanchoi, you can choose the payload type like this
![image](https://cloud.githubusercontent.com/assets/4666935/12491348/84b9a6f8-c02f-11e5-8204-03ae4ac87cbf.png)

**Comment by bryanchoi** [comment] 2016-01-21 19:19
Hi, when I sent via the dashboard, the custom json fields come through on
Android device. This is  the json below.
{
"alert": "John Doe requests to connect with you.",
"email": "bryanchoi@gmail.com"
}

What could be causing it to fail when I send via iOS using sdk?

**Comment by grantland** [comment] 2016-01-21 19:21
It's quite possible it's a bug in the iOS SDK. Have you tried sending the same push that you're sending from the iOS SDK to an iOS device?

**Comment by bryanchoi** [comment] 2016-01-21 19:44
One question to help me test ios to ios device parse push. How can I set
properly set the device_id field of an installation. I'm trying using the
code below, but it doesn't seem to be saving when I check the Installation
table.

PFInstallation *currentInstallation = [PFInstallation currentInstallation];

    [currentInstallation setDeviceTokenFromData:deviceToken];

[currentInstallation setObject:@"9876543210" forKey:@"device_id"];

    [currentInstallation saveInBackground];

**Comment by grantland** [comment] 2016-01-21 19:53
You shouldn't need to set the `deviceToken`, just target the iOS client's current `deviceToken`.

**Comment by bryanchoi** [comment] 2016-01-21 20:07
The push notification doesn't seem to be received when I try iOS to iOS
device. I know it works when I go iOS to android and android sends to iOS.

**Comment by bryanchoi** [comment] 2016-01-21 20:18
One other thing is when I try setting channels for the currentInstallation
on iOS, it doesn't get saved.

**Comment by bryanchoi** [comment] 2016-01-21 20:25
It might help if I set up a skype so you can see exactly what I'm doing.
Let me know if you have time. My skype id is: brychoi7

Bryan

**Comment by bryanchoi** [comment] 2016-01-21 21:22
Hi, so I was able to troubleshoot. From an iOS to another iOS device, i set
data but don't see that in the userInfo dictionary when the notification is
opened. I just see the alert just like in Android. The contents of the
UserInfo dictionary are listed below. There is no custom data... Can you
let me know when there will be a fix for this? I'm trying to get my
prototype up and running for some folks and need this functionality. Thanks

{

    aps =     {

        alert = "Bryan Choi requests to connect with you.";

    };

}

**Comment by bryanchoi** [comment] 2016-01-21 21:24
In addition, I would need to send custom data from Android to another
android device as well as from Android to another iOS device. Thanks

**Comment by grantland** [comment] 2016-01-21 21:35
Since you can send data from the dashboard and is received properly on your Android client, I'm going to be closing this issue since there's nothing out of the ordinary going on in the Android SDK and I recommend opening an issue on our iOS repository.

**Comment by bryanchoi** [comment] 2016-01-21 21:37
what's the link to submit it? you should have a centralized place to submit
bugs? Why do i need to resubmit another one? Can you forward the thread to
it?

**Comment by grantland** [comment] 2016-01-21 23:12
This repo is the codebase for our Android SDK. Our iOS SDK codebase can be found here: https://github.com/ParsePlatform/Parse-SDK-iOS-OSX

As our SDKs are completely different codebases, bugs are submitted and handled in their own repo.

**Comment by bryanchoi** [comment] 2016-01-21 23:17
ok done

**Comment by wangmengyan95** [comment] 2016-01-22 19:24
I will close this issue, feel free to reopen it if you think it is an Android SDK issue,

**Closed by wangmengyan95** 2016-01-22 19:24 UTC
Labels: question

**Comment by bryanchoi** [comment] 2016-01-22 20:55
Can you pass this issue: 783 I created to iOS team? It might be good to
keep the android issue open until the iOS team fixes this so we can verify.
https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/783
