### ISSUE TITLE
Unable to see push opens

### ISSUE THREAD

**Issue by Shailevy** [ParsePlatform/Parse-SDK-Android#175] opened 2015-10-06 14:16 UTC
Hi,
My companies App is using parse for push messages but we override almost all the aspect of push notification UI so our class that extents ParsePushBroadcastReceiver handles most of the elements on its own and calls the super when needed.

I'm unable to get push open events working properly and I'm not sure how to find the problem.
Since I add my own notification UI I don't call a call to onPushOpen so I just call ParseAnalytics.trackAppOpenedInBackground(intent) with my own intent.

In order to verify that the intent hash I'm using (it's a different intent) is Identical I copied the code of getPushHashFromIntent() from your implementation and I print the hash in my receiver's onPushReceive  and I made sure it's the same hash of my the intent I send to trackAppOpenedInBackground.

- My app doesn't has Users
- I call ParseInstallation.getCurrentInstallation().saveInBackground(); on in my App's onCreate() 

Any suggestions ?

**Comment by Shailevy** [comment] 2015-10-11 13:55
I already follow the documentation and I mentioned it in my issue

**Comment by grantland** [comment] 2015-10-14 21:04
There was an backend analytics issue that was fixed last week that prevented push opens from being recorded. If you're still seeing this problem I would recommend to try using the default SDK push logic to determine if the issue is in your application's code or the SDK/backend and if it's in your application's code then to see the other resources listed above.

**Comment by Shailevy** [comment] 2015-10-18 08:25
I still see plenty of user reporting this issue: https://developers.facebook.com/bugs/964772693569483/

**Comment by grantland** [comment] 2015-10-19 18:38
I'll be closing this issue since this is a backend issue and we only track SDK issues in this repository. Please subscribe to the backend issue you've linked.

**Closed by grantland** 2015-10-19 18:38 UTC
Labels: product usage
