### ISSUE TITLE
Parse server: Cloud Functions

### ISSUE THREAD

**Issue by mailmevenkat** [ParsePlatform/Parse-SDK-Android#380] opened 2016-01-30 17:23 UTC
Parse server running at `http://localhost:1337/parse` (tunnelled via ngrok), yields 404 when called from android sdk. Whereas, running parse-server at root "`/`" instead of "`/parse`", works fine. The problem seems to be that, while calling cloud function, sdk ignores the path and takes only the base url.

### Parse server pointing to http://localhost:1337/

![image](https://cloud.githubusercontent.com/assets/9083583/12697209/945f6bb2-c7a3-11e5-8d2e-168fe3263f79.png)

### Parse server pointing to http://localhost:1337/parse

![image](https://cloud.githubusercontent.com/assets/9083583/12697227/2440a4bc-c7a4-11e5-9631-7d00df4f1389.png)

**Comment by smanikandan14** [comment] 2016-01-31 05:31
Yes. I faced this issue too and temp fix this issue in the `index.js` file by replacing `app.use(mountPath, api);` with `app.use(api);`. Just a work around. Proper fix should be on Android SDK side.

**Comment by viktor-skarlatov** [comment] 2016-01-31 14:08
I had the same issue. And its not just cloud functions. For me everything failed with a "Bad json response error". I think the solution is to fix the ParseRESTCommand class so that it doesn't truncate the original URL passed in Parse.Initialize().

**Comment by grantland** [comment] 2016-02-01 17:59
Duplicate of #382

**Closed by grantland** 2016-02-01 17:59 UTC
