### ISSUE TITLE
Push Notification is not working after following Android Tutorial

### ISSUE THREAD

**Issue by venkateshcm** [ParsePlatform/Parse-SDK-Android#165] opened 2015-10-02 03:24 UTC
I followed the tutorial 
https://parse.com/apps/quickstart?app_id=zwibe--3#parse_push/android/native/existing

Don't see any notification on device when sending notifications through parse webapp or from the tutorial test button.

In Webapp, I can see notofications with Pushes Sent as 0 and In delivery report it shows 
1 for PPNS - outdated device

**Comment by alex-maltsev** [comment] 2015-10-11 20:08
I am experiencing the same issue. I simply followed Quick Start instructions here https://parse.com/apps/quickstart#parse_push/android/native/existing, to add some basic ability to receive pushes. After that I spent some of the most frustrating several hours of my life double- and triple-checking that I did everything right. Tested on two devices (both running Lollipop), and I am not getting pushes. Pushes appear in the log on the web. But their delivery reports lists: 0 "Successful deliveries" and 2 "PPNS - outdated device". The app is brand new, and is obviously installed on both devices. I can see Installation objects for both devices, and can selectively target them via a deviceID field that I added onto the Installation object (i.e. when I supply deviceID in web API it tells me that it found the matching Installation). I have Parse version 1.9.3 showing on those Installations. I went through the troubleshooting guide here https://parse.com/docs/android/guide#push-notifications-troubleshooting and I can't find anything wrong with my app.
What can I do?? Why does Parse decide that my Installations are outdated? Can it be because I am adding extra fields to Installations, and somehow Parse decides that something is out of sync??

**Comment by jtuchek** [comment] 2015-10-14 12:44
I was having issues with this as well. Only on initial installations though.

I would follow through with the normal ceremony of setting up all of the Parse required items in my manifest and initialization. Out of curiousity I registered for a save callback to figure out when my device info was getting inserted into the installation table
```
Parse.initialize(context, BuildConfig.PUSH_APPLICATION_ID, BuildConfig.PUSH_CLIENT_KEY);
ParseInstallation.getCurrentInstallation().saveInBackground(new SaveCallback() {
    @Override
    public void done(ParseException e) {
    }
});
```

There seems to be a short instance in which a device can register and become a valid target for push notifications, but they will be undeliverable and consistently yield PPNS errors on delivery reports.

Forcing the application closed and re-opening it (which would invoke the initialization process again) seems to do the trick for overcoming this PPNS issue. Without closing the app it took about 5 minutes or so before it would get notifications (not a predictable amount of time - varying with experimentation)

After testing this I went and inspected 3 of our other projects using bolts 1.2.0 and 1.2.1 as well as Parse v1.9.3

Here's enough of my Manifest + Build info to get a glimpse

```
def final PARSE_APPLICATION_ID = "M4wd7nKLWaHswHFyFRJWT4mp4ncvZYiOe4XdnYan"
def final PARSE_CLIENT_KEY = "iM8xQegOAOa8wtitwlmMed6wcqwX3idR5GzY9Ufi"

android {
    compileSdkVersion 22
    buildToolsVersion '22.0.1'

    defaultConfig {
        applicationId "**************************"
        minSdkVersion 15
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        buildConfigField "String", "BUILD_TIME", "\"${buildTime}\""
        buildConfigField "String", "GIT_SHA", "\"${gitSha()}\""
        buildConfigField "String", "REPORTING_KEY", "\"${CRASH_REPORTING_KEY}\""
        buildConfigField "String", "PUSH_APPLICATION_ID", "\"${PARSE_APPLICATION_ID}\""
        buildConfigField "String", "PUSH_CLIENT_KEY", "\"${PARSE_CLIENT_KEY}\""
    }
}
```

We run multiple build flavors but manifest permissions and categories are templated w/ our applicationId property. Verified correctness of the by checking against artifacts in build > intermediates > manifests for all possible variations.

**Comment by grantland** [comment] 2015-10-14 18:04
First, we'll need to determine if this is a SDK/backend bug or a set up issue:

* Enable logging and paste the output from logcat so we can see if GCM was set up properly: `Parse.setLogLevel(Parse.LOG_LEVEL_VERBOSE)`
* Do your ParseInstallations have a proper `deviceToken` on the backend?
* Does pushing to all your devices as opposed to individual installations instead of individual devices work?

**Comment by alex-maltsev** [comment] 2015-10-15 05:26
One of my colleagues found that putting the following line: `PushService.startServiceIfRequired(this);` after `Parse.initialize` in our Application's onCreate made everything work. But that line isn't described as necessary in the quick-start. So apparently the push service wasn't starting for some reason.
To answer your questions, @grantland.
- When I tried adding `Parse.setLogLevel(Parse.LOG_LEVEL_VERBOSE)`, I didn't see any complaints in logcat
- deviceToken looked reasonable
- pushing to all Android devices didn't work either

**Comment by kardeslik** [comment] 2015-10-15 09:21
@jtuchek @grantland @alex-maltsev 
Hey, not working push is probably related to #192 .

**Comment by adolfdsilva** [comment] 2015-10-19 10:42
Having the same problem, please post a solution soon.

**Comment by grantland** [comment] 2015-10-19 20:02
@alex-maltsev Could you clarify if logcat states you're using GCM or PPNS? If you're using GCM this method shouldn't affect the outcome as it's only relevant to PPNS and if you're using PPNS you should update your code to use GCM.

Also, `PushService.startServiceIfRequired(Context)` is a private API and not recommended to use outside of the Parse SDK as they are subject to breaking changes.

**Comment by majornuts** [comment] 2015-10-20 11:15
okay, same problem here, im working on a new app, with no prior installation of parse push, and followed the 2 minuts minimum imp. tutorial. 
```java
 Parse.setLogLevel(Parse.LOG_LEVEL_VERBOSE);
 Parse.initialize(context, AppController.applicationId, AppController.clientKey);
 ParseInstallation.getCurrentInstallation().saveInBackground(new SaveCallback() {
            @Override
            public void done(ParseException e) {
                Log.e("com.parse.push", "done", e);
            }
        });
```
the above code can registere a user and its shows up as  "ppns outdated" on parse.com.

the verbose log gives the results below. 
V/com.parse.ManifestInfo: **Push is currently disabled.** This is probably because you migrated from an older version of Parse. This version of Parse requires your app to have a BroadcastReceiver that handles com.parse.push.intent.RECEIVE, com.parse.push.intent.OPEN, and com.parse.push.intent.DELETE. You can do this by adding these lines to your AndroidManifest.xml:
V/com.parse.ManifestInfo: Cannot use GCM for push because the app manifest is missing some required declarations. Please make sure that these permissions are declared as children of the root <manifest> element:
V/com.parse.ManifestInfo: Using none for push.


```xml
<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />

<service android:name="com.parse.PushService" />
    <receiver android:name="com.parse.ParsePushBroadcastReceiver"
        android:exported="false">
        <intent-filter>
            <action android:name="com.parse.push.intent.RECEIVE" />
            <action android:name="com.parse.push.intent.DELETE" />
            <action android:name="com.parse.push.intent.OPEN" />
        </intent-filter>
    </receiver>
    <receiver android:name="com.parse.GcmBroadcastReceiver"
        android:permission="com.google.android.c2dm.permission.SEND">
        <intent-filter>
            <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            <action android:name="com.google.android.c2dm.intent.REGISTRATION" />

            <!--
              IMPORTANT: Change "com.parse.starter" to match your app's package name.
            -->
            <category android:name="${package.name}.starter" />
        </intent-filter>
    </receiver>


    <permission android:protectionLevel="signature"
        android:name="${package.name}.permission.C2D_MESSAGE" />
    <uses-permission android:name="${package.name}.permission.C2D_MESSAGE" />
```

```gradle
compile 'com.parse:parse-android:1.10.3'
```

The result is PPNS - outdated result from parse.com.  and no push notifications delivered. 
**BUT, why is it saying im missing the permissions in the manifest file?**

**Comment by adolfdsilva** [comment] 2015-10-20 11:33
Dude you need to replace ${package.name}.starter with your package name.

**Comment by majornuts** [comment] 2015-10-20 13:06
@adolfdsilva  ahh yes that was a mistake,  
now the device shows up on parse.com, **BUT** only when building a signed release of the project. 
**that solved the "PPNS outdated".**
think ill have to change the build setting to build signed debug, and see where that gets me.

**Comment by alex-maltsev** [comment] 2015-10-21 06:49
@grantland I tried again to enable verbose logging, without doing `PushService.startServiceIfRequired(this)`. All I can see in my log related to Parse is this:
>10-20 23:43:44.348 18975-18975/com.**** V/com.parse.ParseHttpClient: Using net.java.URLConnection library for networking communication.
>10-20 23:43:44.450 18975-18975/com.**** V/com.parse.ManifestInfo: Using gcm for push.
>10-20 23:43:44.783 18975-19014/com.**** V/com.parse.ParseInstallation: Successfully deserialized Installation object

Again confirmed that push is not working without `PushService.startServiceIfRequired(this)`.

**Comment by majornuts** [comment] 2015-10-21 08:48
**solution**, I've installed api 23 on the phone and changed the gradle, so that i builds debug and releases with the following buildtype. 

```gradle 
buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            debuggable true
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
```

and the signing Conf. 

```gradle 
signingConfigs {
        release {
            keyAlias 'XXX app'
            keyPassword 'XXX'
            storeFile file('XXX')
            storePassword 'XXX'
        }

    }
```
**apparently parsePush requeries the app to be signed, for the push notifications to work.** 
this crucial detail really should be part of the tutorial... wasted alot of time on this.

**Comment by grantland** [comment] 2015-10-21 22:09
@majornuts signing the debug release shouldn't be necessary with the default push setup. would you happen to be using custom GCM Sender IDs or anything?

**Comment by majornuts** [comment] 2015-10-22 16:06
@grantland  nope no custom GCM Sender ID's, but ive Changed over to a Custom BroadcastReciver.

**Comment by lukewm** [comment] 2015-10-23 10:26
Well tracked down Alex, Can someone update the docs to include this important detail please.

**Comment by NirHUJI** [comment] 2015-10-23 13:25
Same issure here...unsolved yet.

**Comment by majornuts** [comment] 2015-10-23 13:40
@NirHUJI  try enabling the log. 
```java
Parse.setLogLevel(Parse.LOG_LEVEL_VERBOSE);
 Parse.initialize(context, AppController.applicationId, AppController.clientKey);
 ParseInstallation.getCurrentInstallation().saveInBackground(new SaveCallback() {
            @Override
            public void done(ParseException e) {
                Log.e("com.parse.push", "done", e);
            }
        });
```
then follow the errors in permissions, and if there is non of them, then **sign** your debug version of the app. 
someting like i described 2 days ago. in this thread.

**Comment by NirHUJI** [comment] 2015-10-23 16:57
@majornuts I tried signing the apk as you suggested, still doesn't work. I enabled the log and this is what i get this message:

Could not find method android.database.Cursor.getNotificationUri, referenced from method com.parse.ParseSQLiteCursor.getNotificationUri

and this:
Successfully deserialized Installation object
successfully subscribed to the broadcast channel.

**Comment by NirHUJI** [comment] 2015-10-24 14:03
Holy crap! i just found out that i had a subtle typo in the package name in the manifest! dammmmnn it!!
Sorry guys....my bad. now it works!

**Comment by grantland** [comment] 2015-10-26 17:55
@NirHUJI just for confirmation, does it only work with signing enabled or is that not necessary?

**Comment by NirHUJI** [comment] 2015-10-28 16:44
@grantland not necessary...it works without the signing

**Closed** 2015-11-11 17:41 UTC
Labels: product usage

**Comment by rihadavid** [comment] 2015-11-22 23:13
I solved this issue with this code instead what is in instructions (but this is also from Parse Docs, it was there earlier or it is somewhere else, I don't know I just had in in my project from earlier times)

<service android:name="parse.ParsePushService" />
    <receiver android:name="parse.ParsePushBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">
      <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE" />
        <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
        <category android:name="youwakeme.droid" />
      </intent-filter>
    </receiver>

**Comment by harry-saputra** [comment] 2015-11-28 15:29
still no luck till now. spend 4 hours to try many ways from forum, articles, this thread. please help

**Comment by NishanthShankar** [comment] 2015-11-29 14:51
Guys please make sure the services and receiver are inside the application tag. Parse should make this clear in the quick start docs considering that people are new to android

**Comment by TestVTeam** [comment] 2016-01-18 09:48
@grantland: referring to you comment https://github.com/ParsePlatform/Parse-SDK-Android/issues/165#issuecomment-149330096

Does it mean that PPNS will be deprecated? We are planning from GCM to Parse just for PPNS as its independent of Google Play Services. The reason is that in developing countries, where bandwidth is expensive, people restrict backgound data on Google Play Services. This unfortunately blocks GCM too. Further there are many AOSP devices which dont come with Play Services bundled.

While implementing parse, I faced the very same issue of "PPNS device outdate". So need direction on whether PPNS will be retired eventually?

**Comment by wangmengyan95** [comment] 2016-01-22 19:27
Hi @TestVTeam, we still support PPNS, check the details here #197

**Comment by TestVTeam** [comment] 2016-01-25 06:20
@wangmengyan95 Thanks for the confirmation and pointer!
