### ISSUE TITLE
Compiled version 23 gives error when generating signed apk

### ISSUE THREAD

**Issue by iampawan** [ParsePlatform/Parse-SDK-Android#232] opened 2015-11-04 06:16 UTC

**Comment by grantland** [comment] 2015-11-04 06:56
Could this be a duplicate of #231?

**Comment by iampawan** [comment] 2015-11-04 06:59
@grantland  yeah exactly

**Comment by iampawan** [comment] 2015-11-04 07:33
it is the same query as of #231 @grantland @parse-github-bot 
Please fix it .. I have to upload app

**Comment by grantland** [comment] 2015-11-04 07:48
I'll close this since it's a duplicate. See #231 for workaround for now.

**Closed by grantland** 2015-11-04 07:48 UTC
Labels: duplicate
