### ISSUE TITLE
Android 6.0 device doesnt register device token in Installation table

### ISSUE THREAD

**Issue by johnnyzen** [ParsePlatform/Parse-SDK-Android#200] opened 2015-10-20 11:31 UTC
I have noticed that a device with Android 6.0 is not being registered in the installation database. The row is created, but the device token is null and the pushtype is null. The device is a Nexus 5

**Comment by grantland** [comment] 2015-10-20 18:01
To help us debug this issue could you provide the following:

* The version of the Parse SDK this issue is occurring with
* A sample project and steps to reproduce this problem
* Is it only happening on a single device, or many devices?
* Are you able to reliably reproduce this issue?
* Logcat output of the device in question launching the application. You can do this via `Parse.setLogLevel(Parse.LOG_LEVEL_VERBOSE)`

**Comment by xor22h** [comment] 2015-10-21 11:28
Not sure about that. I have the same nexus 5 with marshmallow. I had same issue, but it looks like it was my own issue in AndroidManifest.xml, as I reviewed all the steps how to add push, and it started to work. Seems that it was one of permissions missing.

**Comment by anurag0022** [comment] 2015-11-04 03:54
having same kindof problem... device token is null for android 5.1.1 and android 4.4.4

android manifest:
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="package" >
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
    <uses-permission android:name="android.permission.USE_CREDENTIALS" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />

    <permission android:protectionLevel="signature"
        android:name="package.permission.C2D_MESSAGE" />
    <uses-permission android:name="package.permission.C2D_MESSAGE" />
   <application
        android:name=".MyApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme" >

        <meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />
        <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id" />

        <!--activities->

        <service android:name="com.parse.PushService" />

        <service android:name="com.parse.PushService" />
        <receiver android:name="com.parse.ParsePushBroadcastReceiver"
            android:exported="false">
            <intent-filter>
                <action android:name="com.parse.push.intent.RECEIVE" />
                <action android:name="com.parse.push.intent.DELETE" />
                <action android:name="com.parse.push.intent.OPEN" />
            </intent-filter>
        </receiver>
        <receiver android:name="com.parse.GcmBroadcastReceiver"
            android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />

                <category android:name="package" />
            </intent-filter>
        </receiver>
    </application>

</manifest>


log:
11-04 09:23:27.092 12472-12472/? V/com.parse.ParseHttpClient: Using net.java.URLConnection library for networking communication.
11-04 09:23:27.112 12472-12515/? I/ParseCommandCache: Parse command cache has started processing queued commands.
11-04 09:23:27.122 12472-12472/? V/com.parse.ManifestInfo: Using gcm for push.
11-04 09:23:27.134 12472-12524/? V/com.parse.CachedCurrentInstallationController: Successfully deserialized Installation object
11-04 09:23:27.140 12472-12472/? V/com.parse.GcmRegistrar: Sending GCM registration intent

**Comment by grantland** [comment] 2015-11-04 22:46
@anurag0022 Could you please provide the extra information requested in my previous comment?

**Comment by anurag0022** [comment] 2015-11-05 01:15
@grandland i deleted few rows from parse core and tried  to register devices again but devicetoken is null for all.  Parse sdk 10.3.

**Comment by grantland** [comment] 2015-11-05 01:50
Closing this as not a bug since `pushType` can be `null` if saving the `ParseInstallation` in your own code and the internal SDK calls to save the `pushType` have failed and `deviceToken` can be `null` if the SDK hasn't received GCM registration information from Google Services Framework yet.

FYI deleting `ParseInstallation` objects is not recommended as users with removed `ParseInstallation` objects will need to reinstall the application.

**Closed by grantland** 2015-11-05 01:50 UTC
Labels: needs more info

**Comment by psh-gfm** [comment] 2016-03-01 21:35
This is not a Parse bug, but Parse has done a horrible job at making sure people understand how to properly declare package names. If you follow the tutorial, you will see that Parse tells you to replace 
com.parse.starter with your own package name, but fails to tell you that if you have a build flavor that also needs to be included.

com.parse.starter.debug is one possible permutation of the declaration. Please make sure these match up in your projects.
