### ISSUE TITLE
NPE in com.parse.ParseKeyValueCache.saveToKeyValueCache

### ISSUE THREAD

**Issue by j-koenig** [ParsePlatform/Parse-SDK-Android#132] opened 2015-09-14 14:31 UTC
Hey, 
we are using the Parse Android SDK in version 1.10.1 in our app and we are experiencing some NPEs in our current live version. There is no way to reproduce it reliably but i will attach a stacktrace. The crash does not seem to be platform specific or device specific.

```
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:137)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to get length of null array
	at com.parse.ParseKeyValueCache.saveToKeyValueCache(ParseKeyValueCache.java:141)
	at com.parse.NetworkQueryController$1.then(NetworkQueryController.java:70)
	at com.parse.NetworkQueryController$1.then(NetworkQueryController.java:63)
	at bolts.Task$14.run(Task.java:784)
	at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
	at bolts.Task.completeImmediately(Task.java:775)
	at bolts.Task.continueWith(Task.java:574)
	at bolts.Task.continueWith(Task.java:585)
	at bolts.Task$12.then(Task.java:679)
	at bolts.Task$12.then(Task.java:667)
	at bolts.Task$15.run(Task.java:825)
	... 3 more
```

**Comment by wangmengyan95** [comment] 2015-09-14 17:57
Hi @j-koenig , thanks for opening this issue. For your case, we want to know do you use Local Datastore feature in your app?

**Comment by j-koenig** [comment] 2015-09-15 08:30
Hi @wangmengyan95 , no Local Datastore is disabled for our app.

**Comment by wangmengyan95** [comment] 2015-09-16 17:33
Hi @j-koenig, another reason we can think of is we use your cacheDir/ParseKeyValueCache as the cache folder for the key/value cache. We create this folder when you call `Parse.initialize()`. So in your app, have you ever touched this folder or cleaned the cacheDir manually?

**Comment by julianshen** [comment] 2015-09-17 11:29
We also meet the same issue (1.9.4). It might not be safe if the dir is only created at `Parse.initialize()`. If user clear cache in Settings and switch back to application, it might causes problem. (That's how we reproduce this). Suggest to add codes to re-initialize it if `listFiles()` returns null.

**Comment by j-koenig** [comment] 2015-09-17 13:37
Hey @wangmengyan95 and @julianshen thanks for your posts. I checked the whole app for an access of the cacheDir but I couldn't find any. So I'm pretty sure that we don't touch or clean the cacheDir manually. 

With @julianshen s hint I was able to reproduce the crash:

1. Open the app for the first time -> ParseKeyValue cache gets initialized
2. Do stuff in the app -> entries will be generated in the ParseKeyValue cache
3. Close the app, go to settings, clear app cache
4. Reopen the app, do stuff -> crash

Since this isn't a completely unusual scenario and we as app developers cannot prevent the user from doing this: wouldn't it be best practice to reinitialize the the ParseKeyValue cache if the cacheDir has been cleared?

**Comment by grantland** [comment] 2015-09-17 17:27
This looks to be an actual bug.

@wangmengyan95 Could you also check any other place we use the cache dir?

**Comment by wangmengyan95** [comment] 2015-09-17 17:29
@julianshen @j-koenig , thanks guys, I think this is a valid bug since we can not prevent users to clear the cache dir. 
@grantland , I will check where we use the cache dir.

**Comment by wangmengyan95** [comment] 2015-09-17 21:33
#141

**Comment by j-koenig** [comment] 2015-09-18 08:16
:+1:

**Comment by wangmengyan95** [comment] 2015-09-18 19:38
Landed the PR, @j-koenig maybe use the snapshot and try again? We recreate the cacheDir if it does not exist. Let us know if it works or not.

**Comment by j-koenig** [comment] 2015-09-21 09:01
Tested it -> works! Thanks @wangmengyan95 :+1:

**Comment by wangmengyan95** [comment] 2015-09-21 17:36
Hi @j-koenig, please DO NOT use the snapshot SDK in your production. I am glad it works. I will close this issue right now.

**Closed by wangmengyan95** 2015-09-21 17:36 UTC
Labels: bug
