### ISSUE TITLE
Add support to a self signed certificate

### ISSUE THREAD

**Issue by bilthon** [ParsePlatform/Parse-SDK-Android#440] opened 2016-04-14 18:26 UTC
I've been trying to do this myself for the last couple of days but without much success. I've tried to follow the steps outlined [here](http://developer.android.com/intl/es/training/articles/security-ssl.html#UnknownCa). Using my own certificate created by this command:

`sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/nginx.key -out /etc/ssl/nginx.crt`

I'm using an nginx frontend correctly configured, since I can access the parse-server urls via browser, albeit with the security exception warning.

Does anyone have any advice on how to proceed?

**Comment by shehabic** [comment] 2016-04-17 21:29
Use https://letsencrypt.org/ , it's free, pretty easy to use, open-source and takes only 1 hour to get used to it.

**Comment by Ralphilius** [comment] 2016-05-13 07:41
I am using `Let's Encrypt` but I got `SocketTimeoutException: Read timed out` when calling a cloud function. Not sure if it's really supported.

**Comment by rogerhu** [comment] 2017-03-09 07:57
Duplicate of: https://github.com/ParsePlatform/Parse-SDK-Android/issues/429.  

Please feel free to submit a contribution.  Now that we have standardized on OkHttp3, you should be able to do review https://github.com/square/okhttp/wiki/HTTPS#customizing-trusted-certificates.

**Closed** 2017-03-09 07:57 UTC
Labels: help wanted
